In [2]:
import pandas as pd
df=pd.read_csv('C:\Tekworks\heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [3]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [4]:
x=df.drop(columns='target')
y=df.target
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [5]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
encoders={}
for c in x.select_dtypes(include='object').columns:
    le=LabelEncoder()
    x_train[c]=le.fit_transform(x_train[c])
    x_test[c]=le.transform(x_test)
    encoders[c]=le

In [6]:
num=x_train.select_dtypes(include='number').columns
sc=StandardScaler()
x_train[num]=sc.fit_transform(x_train[num])
x_test[num]=sc.transform(x_test[num])

In [7]:
from sklearn.svm import SVC
svm_linear=SVC(kernel='linear',C=1)
svm_linear.fit(x_train,y_train)
y_pred=svm_linear.predict(x_test)

In [8]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("accuracy: ",accuracy_score(y_test,y_pred))
print("confusion matrix\n",confusion_matrix(y_test,y_pred))

accuracy:  0.8341463414634146
confusion matrix
 [[78 27]
 [ 7 93]]

In [9]:
from sklearn.inspection import DecisionBoundaryDisplay

In [10]:
svm_poly=SVC(kernel='poly',degree=3,C=1)
svm_poly.fit(x_train,y_train)
y_pred=svm_poly.predict(x_test)

In [11]:
print("accuracy_score: ",accuracy_score(y_test,y_pred))
print("confusion matrix\n",confusion_matrix(y_test,y_pred))

accuracy_score:  0.9414634146341463
confusion matrix
 [[100   5]
 [  7  93]]

In [12]:
svm_rbf=SVC(kernel='rbf',gamma='scale',C=1)
svm_rbf.fit(x_train,y_train)
y_pred=svm_rbf.predict(x_test)

In [13]:
print("accuracy_score: ",accuracy_score(y_test,y_pred))
print("confusion matrix\n",confusion_matrix(y_test,y_pred))

accuracy_score:  0.9317073170731708
confusion matrix
 [[97  8]
 [ 6 94]]

In [14]:
import pandas as pd
df=pd.read_csv('train_u6lujuX_CVtuZ9i.csv')
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [15]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [16]:
(df.shape[0]-df.dropna().shape[0])*100/df.shape[0]

21.824104234527688

In [17]:
print(df.dtypes)

Loan_ID                  str
Gender                   str
Married                  str
Dependents               str
Education                str
Self_Employed            str
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area            str
Loan_Status              str
dtype: object

In [18]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [19]:
for i in df.columns:
    print(i,df[i].nunique())

Loan_ID 614
Gender 2
Married 2
Dependents 4
Education 2
Self_Employed 2
ApplicantIncome 505
CoapplicantIncome 287
LoanAmount 203
Loan_Amount_Term 10
Credit_History 2
Property_Area 3
Loan_Status 2

In [22]:
df[['LoanAmount','Loan_Amount_Term']].corr()

                  LoanAmount  Loan_Amount_Term
LoanAmount          1.000000          0.039447
Loan_Amount_Term    0.039447          1.000000

In [33]:
# cols=df.columns[df.isna().mean()>0.1]
# print(cols)
df['Credit_History'].value_counts()
df.fillna({'LoanAmount':df['LoanAmount'].mean()},inplace=True)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.000000,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.000000,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.000000,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.000000,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.000000,360.0,0.0,Semiurban,N

In [34]:
df.fillna(df.mode().iloc[0],inplace=True)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.000000,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.000000,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.000000,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.000000,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.000000,360.0,0.0,Semiurban,N

In [35]:
x=df.drop(columns='Loan_Status')
x=x.drop(columns='Loan_ID')
y=df.Loan_Status

In [36]:
# mask = y.notna()
# x = x[mask]
# y = y[mask]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [37]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
encoders={}
for c in x_train.select_dtypes(include='object').columns:
    le=LabelEncoder()
    x_train[c]=le.fit_transform(x_train[c])
    x_test[c]=le.transform(x_test[c])
    encoders[c]=le
num=x_train.select_dtypes(include='number').columns
sc=StandardScaler()
x_train[num]=sc.fit_transform(x_train[num])
x_test[num]=sc.transform(x_test[num])

C:\Users\728sa\AppData\Local\Temp\ipykernel_20972\2562673864.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for c in x_train.select_dtypes(include='object').columns:

In [38]:
from sklearn.svm import SVC 
svm=SVC(kernel='linear',C=1)
svm.fit(x_train,y_train)
y_pred=svm.predict(x_test)

In [39]:
print("accuracy_score: ",accuracy_score(y_test,y_pred))
print("confusion matrix\n",confusion_matrix(y_test,y_pred))

accuracy_score:  0.7723577235772358
confusion matrix
 [[13 26]
 [ 2 82]]

In [40]:
svm=SVC(kernel='poly',degree=3,C=1)
svm.fit(x_train,y_train)
y_pred=svm.predict(x_test)

In [41]:
print("accuracy_score: ",accuracy_score(y_test,y_pred))
print("confusion matrix\n",confusion_matrix(y_test,y_pred))

accuracy_score:  0.7886178861788617
confusion matrix
 [[16 23]
 [ 3 81]]

In [42]:
svm=SVC(kernel='rbf',gamma='scale',C=1)
svm.fit(x_train,y_train)
y_pred=svm.predict(x_test)

In [43]:
print("accuracy_score: ",accuracy_score(y_test,y_pred))
print("confusion matrix\n",confusion_matrix(y_test,y_pred))

accuracy_score:  0.7804878048780488
confusion matrix
 [[13 26]
 [ 1 83]]